[tool.poetry]
name = "reviewpoint-docs"
version = "0.1.0"
description = "Documentation for the ReViewPoint project"
authors = ["Filip Herceg <pvt.filip.herceg@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.13"
mypy = "^1.10"

[tool.mypy]
python_version = "3.11"
namespace_packages = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
